restart_file: .na
sim_name: test
forecast_days: 0
start_day_local: 2018-07-12
start_time_local: 07:00:00
end_day_local: 2018-07-15
forecast_start_day_local: 2018-07-15
forecast_project_id: test
forecast_sss_on: FALSE
forecast_location: /Users/quinn/Dropbox/Research/SSC_forecasting/run_flare_package
execute_location: /Users/quinn/Dropbox/Research/SSC_forecasting/run_flare_package
