file_path:
   qaqc_data_directory: .na
   noaa_directory: .na
   inflow_directory: .na
   configuration_directory: .na
   execute_directory: .na
   forecast_output_directory: .na
s3:
  drivers:
    endpoint: s3.flare-forecast.org
    bucket: drivers
  analysis:
    endpoint: s3.flare-forecast.org
    bucket: analysis
  targets:
    endpoint: s3.flare-forecast.org
    bucket: targets
  forecasts:
    endpoint: s3.flare-forecast.org
    bucket: forecasts
  forecasts_csv:
    endpoint: s3.flare-forecast.org
    bucket: forecasts-csv
  warm_start:
    endpoint: s3.flare-forecast.org
    bucket: restart
  scores:
    endpoint: s3.flare-forecast.org
    bucket: scores
location:
   site_id: fcre
   name: Falling Creek Reservoir
   latitude: 37.307   #Degrees North
   longitude: -79.837  #Degrees East
metadata:
   generate_eml: TRUE
   forecast_project_id: test
   abstract: "This is where a longer description of the forecast can be added"
   forecast_title: FLARE
   intellectualRights: MIT
   model_description:
      forecast_model_id: https://github.com/rqthomas/flare/commit/d1ddcb07b9d28863890597503fc4aa4a4496de56
      name: General Lake Model
      type: process-based
      repository: https://github.com/AquaticEcoDynamics/GLM/releases/tag/v3.1.0
   me:
      individualName:
         givenName: "Quinn"
         surName: "Thomas"
      electronicMailAddress:  "INSERT"
      id: INSERT ORCID
da_setup:
    da_method: enkf
    par_fit_method: inflate
    ensemble_size:  200
    localization_distance: .na #distance in meters were covariances in the model error are used
    no_negative_states: TRUE
    assimilate_first_step: FALSE
    use_obs_constraint: TRUE
model_settings:
   ncore: 2
   model_name: glm
   base_GLM_nml: glm3.nml
   modeled_depths:
   - 0.00
   - 0.25
   - 0.50
   - 0.75
   - 1.00
   - 1.25
   - 1.50
   - 1.75
   - 2.00
   - 2.25
   - 2.50
   - 2.75
   - 3.00
   - 3.25
   - 3.50
   - 3.75
   - 4.00
   - 4.25
   - 4.50
   - 4.75
   - 5.00
   - 5.25
   - 5.50
   - 5.75
   - 6.00
   - 6.25
   - 6.50
   - 6.75
   - 7.00
   - 7.25
   - 7.50
   - 7.75
   - 8.00
   - 8.25
   - 8.50
   - 8.75
   - 9.00
   - 9.25
   par_config_file: parameter_calibration_config.csv
   obs_config_file: observations_config.csv
   states_config_file: states_config.csv
   depth_model_sd_config_file: depth_model_sd.csv
default_init:
   lake_depth: 9.4  #not a modeled state
   temp: [25.667, 24.9101, 23.067, 21.8815, 19.6658, 16.5739, 12.9292, 12.8456, 12.8127, 12.8079, 12.778]
   temp_depths: [0.127, 1.004, 2.005, 3.021, 4.002, 5.004, 6.004, 7.01, 8.001, 9.015, 9.518]
   salinity: 0.0
   snow_thickness: 0.0
   white_ice_thickness: 0.0
   blue_ice_thickness: 0.0
inflow:
   use_forecasted_inflow: TRUE
   forecast_inflow_model: inflow/FLOWS-NOAAGEFS-AR1
met:
   use_forecasted_met: TRUE
   forecast_met_model: noaa/NOAAGEFS_1hr-debias
   historical_met: observed
uncertainty:
   observation: TRUE
   process: TRUE
   weather: TRUE
   initial_condition: TRUE
   parameter: TRUE
   met_downscale: TRUE
   inflow_process: TRUE
output_settings:
   diagnostics_names:  [extc]
